# Configure libcluster
# PORT=4000 iex --sname a -S mix phx.server
# PORT=4001 iex --sname b -S mix phx.server
import Config

config :libcluster, topologies: [gossip: [strategy: Cluster.Strategy.Gossip]]

# Do not include metadata nor timestamps in development logs
config :logger, :default_formatter, format: "[$level] $message\n"

# Initialize plugs at runtime for faster development compilation
# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :plug_init_mode, :runtime
config :phoenix, :stacktrace_depth, 20

# https://github.com/crbelaus/bun/pull/46/files
config :phoenix_live_view, :colocated_js,
  target_directory: Path.expand("../assets/node_modules/phoenix-colocated", __DIR__)

config :phoenix_live_view,
  # Include debug annotations and locations in rendered markup.
  # Changing this configuration will require mix clean and a full recompile.
  debug_heex_annotations: true,
  debug_attributes: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true

# Configure your database
config :profile, Profile.Repo,
  hostname: "localhost",
  database: "profile_dev",
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :profile, ProfileWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "dQmoP5LO6f0/hWaHpqQ64L4zAx/iNmFihi512n2t1o5Nl8a+tDDNf57SMBVrdZxv",
  watchers: [
    bun_css: {Bun, :install_and_run, [:css, ~w(--watch)]},
    bun_js: {Bun, :install_and_run, [:js, ~w(--sourcemap=inline --watch)]}
  ]

# Reload browser tabs when matching files change.
# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
config :profile, ProfileWeb.Endpoint,
  live_reload: [
    web_console_logger: true,
    patterns: [
      # Static assets, except user uploads
      #
      #     mix phx.gen.cert
      ~r"priv/static/(?!uploads/).*\.(js|css|png|jpeg|jpg|gif|svg)$"E,
      # Gettext translations
      #
      # Run `mix help phx.gen.cert` for more information.
      ~r"priv/gettext/.*\.po$"E,
      # Router, Controllers, LiveViews and LiveComponents
      #
      # The `http:` config above can be replaced with:
      #
      #     https: [
      #       port: 4001,
      #       cipher_suite: :strong,
      ~r"lib/profile_web/router\.ex$"E,
      ~r"lib/profile_web/(controllers|live|components)/.*\.(ex|heex)$"E
    ]
  ]

# Enable dev routes for dashboard and mailbox
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
config :profile, dev_routes: true

# Disable swoosh api client as it is only required for production adapters.
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

config :swoosh, :api_client, false
